Element84/filmdrop-ui

.env.development, .env.production, README.md, package-lock.json, package.json, src/components/Layout/Content/BottomContent/BottomContent.js, src/components/Layout/PageHeader/PageHeader.js, src/components/LeafMap/LeafMap.css, src/components/LeafMap/LeafMap.js, src/components/Search/Search.js
Moved hardcoded values for STAC API endpoint, collections name and button URLs into environment variables.  This PR also resolves issue #1 .
=> Updates for version 0.2.0 and fix for #1

.env.example, CHANGELOG.md, README.md, src/components/Layout/Content/BottomContent/BottomContent.css, src/components/Layout/Content/BottomContent/BottomContent.js, src/components/Search/Search.js, src/redux/slices/mainSlice.js
1.  Remove BBOX button and functionality
2.  Add zoom notice and minimum zoom level for search
=> Remove bbox button

CHANGELOG.md, src/components/CloudSlider/CloudSlider.js, src/components/Layout/Content/BottomContent/BottomContent.css, src/components/Layout/Content/Content.css, src/components/Layout/Content/TopContent/TopContent.css, src/components/Layout/PageHeader/PageHeader.css, src/components/Search/Search.css, src/components/Search/Search.js
- #31 Fix calendar z-index
1. Remove search button
2. Perform search after filters change, on zoom end or on drag end
=> Remove search button, update styling

public/index.html, src/components/CollectionDropdown/CollectionDropdown.css, src/components/CollectionDropdown/CollectionDropdown.js, src/components/Search/Search.css, src/components/Search/Search.js
- #32 
1. Update site title to pull from env variable
2. Style tweaks for collection dropdown, date picker
=> Update site title, css tweaks

src/components/Search/Search.js
- #43 
1.  Allow zoom on double-click
=> Fix doubleclick zoom on image

package-lock.json, src/components/CollectionDropdown/CollectionDropdown.js, src/components/LaunchModal/LaunchModal.css, src/components/PopupResult/PopupResult.css, src/components/PopupResult/PopupResult.js, src/components/Search/Search.js, src/redux/slices/mainSlice.js, src/utils/datetime.js
- n/a
1. Add support for sar:polarization if available for collection
=> Add support for sar:polarizations, code cleanup

CHANGELOG.md, package-lock.json, package.json, src/components/CollectionDropdown/CollectionDropdown.js, src/components/Search/Search.css, src/components/Search/Search.js, src/components/Search/react-calendar-overrides.css, src/redux/slices/mainSlice.js
- n/a
1.  If viewport is out of collection spatial bounds, move the viewport to include collection bounds.
2. If date range is out of collection temporal bounds, set the date range to the start and end of collection date range.
=> Add collection date and bbox ranges

CHANGELOG.md, package-lock.json, package.json, src/components/LeafMap/LeafMap.css, src/components/LeafMap/LeafMap.js, src/components/Search/Search.css, src/components/Search/Search.js, src/components/Search/react-calendar-overrides.css, src/redux/slices/mainSlice.js
- N/A
1. Add geosearch functionality
2. Move map attribution into a hoverable icon
=> Add geosearch and attribution icon

CHANGELOG.md, package-lock.json, package.json
- n/a
1. release prep for 1.0.0
=> prep for 1.0.0 release

src/components/CollectionDropdown/CollectionDropdown.css
- N/A
1.  Fix css styling on collections dropdown for Windows
=> Fix collection dropdown on windows

package-lock.json, package.json, src/components/Search/Search.js
- N/A
1.  Update datetimerange picker to 5.0.1
=> Update datetimerange picker to 5.0.1

package-lock.json, package.json
- N/A
1.  Remove unused web-vitals from dependencies
=> Remove web-vitals

src/components/Search/Search.js, src/components/Search/SearchParameters.js
- #117 
1. Add limit to mosaic parameters
=> Add parameters for mosaic search

src/components/Search/Search.js, src/components/Search/SearchParameters.js
- N/A
1. Fix query parameter on auto search 
=> Fix sar polarizations query

CHANGELOG.md, src/utils/datetime.js
- n/a
1. fix datetime range to cover all of the start and end dates
=> fix datetime range to do what you'd expect

src/components/CollectionDropdown/CollectionDropdown.jsx
- NA
1. refactor mapCollection function to avoid possible prototype pollution
=> fix possible prototype pollution

package.json
- n/a
1. remove ignored vulnerability as it has been resolved.
=> remove vulnerability ignore as it as been resolved

CHANGELOG.md, package-lock.json, package.json
- n/a
1. release prep for 2.0.0
=> release prep 2.0.0

CHANGELOG.md, package-lock.json, package.json
- n/a
1. release prep for 2.0.1
2.
=> release prep for 2.0.1

CHANGELOG.md, src/components/Layout/Content/BottomContent/BottomContent.jsx
- n/a
1. Fix publish button to appear with boolean `true` value instead of string `"true"`
=> fix display of publish button

CHANGELOG.md, package-lock.json, package.json
=> release prep 2.0.2

package-lock.json, package.json
=> Update package.lock to resolve GHSA-353f-5xf4-qw67

CHANGELOG.md, README.md, src/utils/mapHelper.js
- n/a
1. Update titiler parameters to work with >= 0.11.x titiler 
=> fix titiler parameters for 0.11.x api

CHANGELOG.md
- n/a
- update DOQQ grid file with Hawaii
=> update DOQQ file with hawaii

CHANGELOG.md, package-lock.json, package.json
- n/a
1. Release prep for 3.0.0
=> release prep for 3.0.0

CHANGELOG.md, package-lock.json, package.json
- n/a
1. Release prep or v3.1.0
=> release prep 3.1.0

CHANGELOG.md, package-lock.json, package.json
- n/a
1. release prep for 3.2.0
=> 3.2.0 release preop

README.md
- n/a
1. Add more documentation on features
=> add feature configuration section

CHANGELOG.md, package-lock.json, package.json
- NA
1. Release prep for 4.0.1
2. Pushed to fix bug in grid-code click events not selection scenes
=> 4.0.1 release prep

CHANGELOG.md, package-lock.json, package.json
- NA
1. Release prep for v4.1.0
=> release prep for 4.1.0

ADRs/adr_config_refactor_11.8.23.md, ADRs/adr_design_refactor_11.2.23.md
- NA
1. Added first ADR for decision on moving to scalable frontend architecture 🥳 
=> Adding ADR: proposed for more scalable architecture 

CHANGELOG.md, package-lock.json, package.json
- n/a
1. pre-release prep for 4.4.0
=> release prep for 4.4.0

CHANGELOG.md, package-lock.json, package.json
=> release prep 5.0.0

CHANGELOG.md, package-lock.json, package.json
=> release prep 5.0.1

CHANGELOG.md, package-lock.json, package.json
=> release prep 5.0.2

CHANGELOG.md, package-lock.json, package.json
- n/a
1. release prep for 5.1.0
=> release prep 5.1.0

CHANGELOG.md, package-lock.json, package.json
=> release prep 5.2.0

CHANGELOG.md
- n/a
release prep for 5.3.0
- [S] I have added my changes to the [CHANGELOG](https://github.com/Element84/filmdrop-ui/blob/main/CHANGELOG.md) **or** a CHANGELOG entry is not required.
=> release prep for 5.3.0

CHANGELOG.md, package-lock.json
- NA
1. resolves 2 high npm vulnerabilities 
=> Fix high npm vulnerabilities

CHANGELOG.md, package.json
=> release prep for 5.6.0

CHANGELOG.md, package-lock.json, package.json
- NA
1. release prep for 5.7.0
=> release prep for 5.7.0

CHANGELOG.md, package-lock.json, package.json
- #406 
1. release prep for 5.7.1
=> Release prep 5.7.1

CHANGELOG.md, package-lock.json, package.json
- None
1. Update CHANGELOG.md to show release 6.0.0 heading.
2. Update version number in package.json and package-lock.json
=> Release prep for 6.0.0
